# Generated by Django 3.2.4 on 2021-06-19 18:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('seller', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessdetails',
            name='address_proof',
            field=models.ImageField(upload_to='seller_details/address_proof'),
        ),
        migrations.AlterField(
            model_name='companydetails',
            name='seller',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='CompanyDetails', serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
