# Generated by Django 3.2.3 on 2021-06-16 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0003_auto_20210616_1404'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessdetails',
            name='address_l1',
            field=models.CharField(max_length=300, verbose_name='Address Line 1'),
        ),
        migrations.AlterField(
            model_name='businessdetails',
            name='address_l2',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Address Line 2'),
        ),
        migrations.AlterField(
            model_name='products',
            name='product_image',
            field=models.ImageField(upload_to='seller/static/seller/images/uploads/products'),
        ),
    ]
